[package]
name = "rust"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]

[lib]
name="rust"
crate-type=["cdylib"]

[build-dependencies]
bindgen="0.56.0"

[dependencies]
cfs-sys = { path = "/host/cfs-sys" }

[profile.release]
lto=true
panic='abort'
